openapi: 3.0.0

info:
  title: Mitum API
  version: '0.0.1'
  description:
    $ref: 'introduction.yaml#/introduction'

  contact:
    name: SocialInfraTech Support
    email: dev@socialinfratech.com
    url: *****
  license:
    name: *****
    url: *****
  termsOfService: *****

servers:
  - url: *****
    description: Production
  - url: https://testnet.protocon.io
    description: Sandbox

tags:
  - name: Node Info
    description: The information about the mitum node that is currently providing the service.
  - name: Block
    description: The information about the blocks that have completed consensus and the operations they contain.
  - name: Account
    description: The information about the status of accounts.
  - name: Builder
    description: Create, sign, and broadcast an operation.
  - name: Currency
    description: The currency information.
  - name: Contract
    description: The information about the status of contract-accounts.
  - name: Credential
    description: The information about the status of the Credential services.
  - name: NFT
    description: The information about the status of the NFT services.
  - name: KYC
    description: The information about the status of the KYC services.
  - name: Security-Token
    description: The information about the status of the ST services.
  - name: Timestamp
    description: The information about the status of the Timestamp services.
  - name: DAO
    description: The information about the status of the DAO services.
  - name: Point
    description: The information about the status of the Point services.

paths:
  /:
    get:
      $ref: "./nodeinfo/nodeinfo.yaml"

  /block/{height}:
    get:
      $ref: "./block/block_by_height.yaml"

  /block/{block_hash}:
    get:
      $ref: "./block/block_by_hash.yaml"

  /block/{height}/manifest:
    get:
      $ref: "./block/block_manifest_by_height.yaml"
  
  /block/operation/{operation_fact_hash}:
    get:
      $ref: "./block/block_operation_by_hash"

  /block/manifests:
    get:
      $ref: "./block/all_manifests.yaml"
  
  /block/{height}/operations:
    get:
      $ref: "./block/all_operations_of_block.yaml"

  /block/operations:
    get:
      $ref: "./block/all_operation.yaml"
  
